{{- if .Values.global.vault.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
  labels:
    {{- include "maf.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.global.vault.server }}
      path: {{ .Values.global.vault.path }}
      version: v2
      auth:
        kubernetes:
          mountPath: {{ .Values.global.vault.auth.kubernetes.mountPath }}
          role: {{ .Values.global.vault.auth.kubernetes.role }}
          serviceAccountRef:
            name: {{ .Values.global.vault.auth.kubernetes.serviceAccount }}
            namespace: {{ .Release.Namespace }}
{{- end }}