{{- if .Values.global.vault.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: maf-runtime
spec:
  secretStoreRef: { name: vault, kind: ClusterSecretStore }
  target: { name: maf-runtime, creationPolicy: Owner }
  data:
    {{- range .Values.api.externalSecrets.data }}
    - secretKey: {{ .target }}
      remoteRef: { key: {{ .remoteRef.path }}, property: {{ .remoteRef.key }} }
    {{- end }}
{{- end }}
