import os, asyncio, json
import nats
import redis.asyncio as redis
from datetime import datetime
import sys
sys.path.append('/app')
from memory.vector_store import search_by_text
from llm.openai_helpers import generate_markdown

NATS_URL   = os.getenv("NATS_URL", "nats://nats:4222")
ROLE       = os.getenv("AGENT_ROLE", "compliance_checker")
SUBJECT    = f"tasks.{ROLE}"
REDIS_HOST = os.getenv("REDIS_HOST", "redis")
REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))

r = redis.Redis(host=REDIS_HOST, port=REDIS_PORT, decode_responses=True)

async def main():
    nc = await nats.connect(NATS_URL)
    js = nc.jetstream()

    async def handle(msg):
        data = json.loads(msg.data.decode())
        task_id = data["task_id"]
        payload = data["payload"]

        # set status: processing
        await r.hset(f"task:{task_id}", mapping={"status":"processing","role":ROLE})

        print(f"[{ROLE}] Received task {task_id}: {payload}")

        try:
            # Extract task details
            description = payload.get('description', 'No description provided')
            compliance_type = payload.get('compliance_type', 'general')
            standards = payload.get('standards', [])
            code_to_check = payload.get('code_to_check', '')
            
            # Fetch relevant context from vector store
            context_results = []
            if description:
                try:
                    context_results = search_by_text(description, limit=5)
                except Exception as e:
                    print(f"[{ROLE}] Context fetch error: {e}")
            
            # Prepare context for LLM
            context_text = "\n".join([
                f"- {result.get('content', '')[:200]}..." 
                for result in context_results
            ]) if context_results else "No relevant context found."
            
            # Generate compliance check using LLM
            prompt = f"""You are an expert compliance auditor. Perform a comprehensive compliance review.

Task Description: {description}
Compliance Type: {compliance_type}
Standards: {', '.join(standards) if standards else 'General compliance standards'}
Code to Check: {code_to_check[:500] if code_to_check else 'No specific code provided'}

Relevant Context:
{context_text}

Provide a detailed compliance assessment including:
1. Compliance checklist and requirements
2. Code review findings
3. Security vulnerabilities
4. Data privacy compliance (GDPR, CCPA)
5. Industry standards adherence
6. Remediation recommendations
7. Risk assessment and mitigation

Format the response as structured markdown with clear sections and severity levels."""
            
            # Call LLM for compliance analysis
            result_content = generate_markdown(prompt, max_tokens=4000)
            
            # Add metadata to result
            result_content += f"\n\n---\n**Generated by:** {ROLE}\n**Context sources:** {len(context_results)}\n**Compliance Type:** {compliance_type}\n**Timestamp:** {datetime.utcnow().isoformat()}"
            
        except Exception as e:
            print(f"[{ROLE}] LLM processing error: {e}")
            result_content = f"# Compliance Check Task\n\nError processing request: {str(e)}\n\nFallback output based on payload: {payload}"

        # Publish result via JetStream
        result_subject = f"results.{ROLE}.{task_id}"
        await js.publish(result_subject, json.dumps({
            "task_id": task_id,
            "role": ROLE,
            "result": result_content
        }).encode())

        await msg.ack()  # tell JS we processed this message
        print(f"[{ROLE}] Published result to {result_subject}")

    # Durable + queue group = load-balanced & replayable
    await js.subscribe(SUBJECT, durable=ROLE, queue=ROLE, cb=handle, manual_ack=True)
    print(f"[{ROLE}] Listening on {SUBJECT} (durable={ROLE}, queue={ROLE}) ...")

    while True:
        await asyncio.sleep(1)

if __name__ == "__main__":
    asyncio.run(main())