apiVersion: v1
kind: ConfigMap
metadata:
  name: maf-router
  labels:
    {{- include "maf.labels" . | nindent 4 }}
data:
  models.yaml: |
{{ toYaml .Values.router.models | indent 4 }}
  model_router.yaml: |
{{ toYaml .Values.router.policies | indent 4 }}
