{{- if .Values.global.vault.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.vault.auth.kubernetes.serviceAccount }}
  labels:
    {{- include "maf.labels" . | nindent 4 }}
{{- end }}